import { createContext, useContext, useState, useEffect } from 'react'

const LanguageContext = createContext()

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}

const translations = {
  en: {
    // Auth Component
    auth: {
      welcomeBack: 'Welcome Back',
      createAccount: 'Create Account',
      signInSubtitle: 'Sign in to your account',
      createAccountSubtitle: 'Start your cold email campaigns',
      continueWithGoogle: 'Continue with Google',
      or: 'or',
      email: 'Email',
      password: 'Password',
      signIn: 'Sign In',
      signUp: 'Sign Up',
      forgotPassword: 'Forgot password?',
      dontHaveAccount: "Don't have an account?",
      alreadyHaveAccount: 'Already have an account?',
      checkEmailConfirmation: 'Check your email for the confirmation link!',
      backToLanding: 'Back to Homepage'
    },

    // Dashboard
    dashboard: {
      title: 'Dashboard',
      welcome: 'Welcome to Contactium',
      quickStats: 'Quick Stats',
      totalCampaigns: 'Total Campaigns',
      runningCampaigns: 'Running',
      completedCampaigns: 'Completed',
      emailsSent: 'Emails Sent',
      recentCampaigns: 'Recent Campaigns',
      viewAll: 'View All',
      createCampaign: 'Create New Campaign',
      noCampaigns: 'No campaigns yet',
      noCampaignsDesc: 'Create your first campaign to start sending cold emails',
      status: 'Status',
      recipients: 'Recipients',
      sent: 'Sent',
      actions: 'Actions',
      send: 'Send',
      view: 'View',
      sending: 'Sending...',
      confirmSend: 'Are you sure you want to send',
      confirmSendDetails: 'This will generate and send personalized emails to all recipients.',
      campaignLimitReached: 'Campaign limit reached! You have',
      campaignLimitOf: 'of',
      campaignLimitUpgrade: 'campaigns. Upgrade your plan to create more campaigns.',
      sendSuccess: 'Campaign sent successfully!',
      emailsSentCount: 'emails sent',
      emailsFailedCount: 'failed',
      sendFailed: 'Failed to send campaign:',
      expired: 'Expired',
      expiresIn: 'Expires in',
      days: 'days'
    },

    // Campaigns
    campaigns: {
      title: 'Campaigns',
      searchPlaceholder: 'Search campaigns...',
      filter: 'Filter',
      all: 'All',
      draft: 'Draft',
      running: 'Running',
      completed: 'Completed',
      paused: 'Paused',
      noCampaigns: 'No campaigns found',
      createFirst: 'Create your first campaign',
      name: 'Name',
      status: 'Status',
      recipients: 'Recipients',
      sent: 'Sent',
      createdAt: 'Created',
      actions: 'Actions'
    },

    // Create Campaign
    createCampaign: {
      title: 'Create New Campaign',
      step: 'Step',
      of: 'of',
      campaignDetails: 'Campaign Details',
      selectContacts: 'Select Contacts',
      emailSettings: 'Email Settings',
      reviewAndCreate: 'Review & Create',
      campaignName: 'Campaign Name',
      campaignNamePlaceholder: 'Enter campaign name',
      selectContactList: 'Select Contact List',
      selectContactListPlaceholder: 'Choose a contact list',
      noContactLists: 'No contact lists available',
      createContactList: 'Create a contact list first',
      selectedContacts: 'Selected Contacts',
      emailSubject: 'Email Subject',
      emailSubjectPlaceholder: 'Enter email subject',
      valueProposition: 'Value Proposition',
      valuePropositionPlaceholder: 'Describe your value proposition for AI to generate personalized emails',
      aiModel: 'AI Model',
      selectModel: 'Select AI model',
      tone: 'Tone',
      selectTone: 'Select tone',
      professional: 'Professional',
      friendly: 'Friendly',
      casual: 'Casual',
      formal: 'Formal',
      length: 'Email Length',
      selectLength: 'Select length',
      short: 'Short',
      medium: 'Medium',
      long: 'Long',
      language: 'Language',
      selectLanguage: 'Select language',
      back: 'Back',
      continue: 'Continue',
      createCampaign: 'Create Campaign',
      creating: 'Creating...',
      fillAllFields: 'Please fill in all required fields',
      campaignCreated: 'Campaign created successfully!',
      errorCreating: 'Error creating campaign:'
    },

    // Contact Lists
    contactLists: {
      title: 'Contact Lists',
      createNew: 'Create New List',
      searchPlaceholder: 'Search contact lists...',
      noLists: 'No contact lists yet',
      createFirst: 'Create your first contact list to organize your contacts',
      name: 'Name',
      contacts: 'Contacts',
      createdAt: 'Created',
      actions: 'Actions',
      view: 'View',
      edit: 'Edit',
      delete: 'Delete',
      confirmDelete: 'Are you sure you want to delete this contact list?',
      deleteSuccess: 'Contact list deleted successfully',
      deleteError: 'Error deleting contact list'
    },

    // Companies (Database)
    companies: {
      title: 'Company Database',
      subtitle: 'Browse and select companies from our verified database',
      searchPlaceholder: 'Search companies...',
      filterByIndustry: 'Filter by Industry',
      allIndustries: 'All Industries',
      filterByCity: 'Filter by City',
      allCities: 'All Cities',
      showing: 'Showing',
      of: 'of',
      companies: 'companies',
      noCompanies: 'No companies found',
      adjustFilters: 'Try adjusting your search or filters',
      companyName: 'Company Name',
      industry: 'Industry',
      city: 'City',
      email: 'Email',
      phone: 'Phone',
      actions: 'Actions',
      addToList: 'Add to List',
      selectList: 'Select a contact list',
      companyAdded: 'Company added to contact list',
      errorAdding: 'Error adding company to list'
    },

    // Settings
    settings: {
      title: 'Settings',
      profile: 'Profile',
      smtp: 'SMTP Configuration',
      subscription: 'Subscription & Billing',
      emailSettings: 'Email Settings',
      profileEmail: 'Email',
      profileName: 'Name',
      profileNamePlaceholder: 'Your name',
      save: 'Save Changes',
      saving: 'Saving...',
      saved: 'Settings saved successfully',
      smtpHost: 'SMTP Host',
      smtpHostPlaceholder: 'smtp.gmail.com',
      smtpPort: 'SMTP Port',
      smtpPortPlaceholder: '587',
      smtpUser: 'SMTP Username',
      smtpUserPlaceholder: 'your-email@gmail.com',
      smtpPassword: 'SMTP Password',
      smtpPasswordPlaceholder: 'Your app password',
      smtpSecure: 'Use SSL/TLS',
      testConnection: 'Test Connection',
      testing: 'Testing...',
      connectionSuccess: 'SMTP connection successful!',
      connectionFailed: 'SMTP connection failed:',
      smtpInstructions: 'Configure your SMTP settings to send emails. For Gmail, use an app-specific password.',
      fromName: 'From Name',
      fromNamePlaceholder: 'Your Company',
      fromEmail: 'From Email',
      fromEmailPlaceholder: 'you@company.com'
    },

    // Subscription (already exists but adding missing translations)
    subscription: {
      title: 'Subscription & Billing',
      subtitle: 'Manage your subscription and view usage',
      currentPlan: 'Current Plan',
      freePlan: 'Free Plan',
      starterPlan: 'Starter Plan',
      professionalPlan: 'Professional Plan',
      active: 'Active',
      canceled: 'Canceled',
      pastDue: 'Payment Due',
      monthlyUsage: 'Monthly Email Usage',
      emailsSent: 'emails sent',
      remaining: 'remaining',
      limitReached: 'Limit reached',
      upgradePrompt: "You've reached your monthly email limit. Upgrade to send more emails.",
      lowEmailsWarning: 'Running low on emails? Upgrade to continue your campaigns without interruption.',
      upgradeTo: 'Upgrade to',
      manageSubscription: 'Manage Subscription',
      billingInfo: 'Billing Information',
      nextBillingDate: 'Next Billing Date',
      amount: 'Amount',
      paymentMethod: 'Payment Method',
      recentInvoices: 'Recent Invoices',
      paid: 'Paid',
      pending: 'Pending',
      void: 'Void',
      failed: 'Failed',
      downloadPDF: 'PDF',
      haveCoupon: 'Have a Coupon Code?',
      enterCoupon: 'Enter coupon code',
      couponApplied: 'Coupon code will be applied at checkout',
      cancelAnytime: 'You can cancel or modify your subscription anytime through the customer portal. No long-term commitments required.',
      whyUpgrade: 'Why Upgrade?',
      benefit1: 'Send more emails and reach more prospects',
      benefit2: 'Manage multiple campaigns simultaneously',
      benefit3: 'Unlimited AI-powered email generation',
      benefit4: 'Scale your cold email outreach',
      benefit5: 'Priority email support'
    },

    // Support
    support: {
      title: 'Help & Support',
      searchPlaceholder: 'Search for help...',
      gettingStarted: 'Getting Started',
      gettingStartedDesc: 'Learn the basics of Contactium',
      campaigns: 'Campaign Management',
      campaignsDesc: 'Creating and managing campaigns',
      contacts: 'Contact Management',
      contactsDesc: 'Organizing your contact lists',
      smtp: 'SMTP Setup',
      smtpDesc: 'Configuring email sending',
      billing: 'Billing & Plans',
      billingDesc: 'Subscription and payment help',
      contactSupport: 'Contact Support',
      contactSupportDesc: 'Get help from our team',
      sendMessage: 'Send us a message',
      subject: 'Subject',
      subjectPlaceholder: 'How can we help?',
      message: 'Message',
      messagePlaceholder: 'Describe your issue or question...',
      send: 'Send Message',
      sending: 'Sending...',
      messageSent: 'Message sent successfully! We\'ll get back to you soon.',
      messageError: 'Error sending message. Please try again.'
    },

    // Admin Panel
    admin: {
      title: 'Admin Panel',
      overview: 'Overview',
      users: 'Users',
      coupons: 'Coupons',
      support: 'Support Messages',
      totalUsers: 'Total Users',
      freeUsers: 'Free Plan',
      paidUsers: 'Paid Plans',
      totalRevenue: 'Total Revenue',
      searchUsers: 'Search users...',
      filterPlan: 'Filter by Plan',
      allPlans: 'All Plans',
      email: 'Email',
      plan: 'Plan',
      status: 'Status',
      joined: 'Joined',
      actions: 'Actions',
      createCoupon: 'Create Coupon Code',
      couponCode: 'Coupon Code',
      couponCodePlaceholder: 'SUMMER2024',
      discountType: 'Discount Type',
      percentOff: 'Percent Off',
      amountOff: 'Amount Off',
      percentValue: 'Percent Off (%)',
      percentPlaceholder: '20',
      amountValue: 'Amount Off (€)',
      amountPlaceholder: '10',
      duration: 'Duration',
      once: 'Once',
      repeating: 'Repeating',
      forever: 'Forever',
      durationMonths: 'Duration (Months)',
      maxRedemptions: 'Max Redemptions',
      maxRedemptionsPlaceholder: 'Leave empty for unlimited',
      expiresAt: 'Expires At',
      createCouponBtn: 'Create Coupon',
      creating: 'Creating...',
      activeCoupons: 'Active Coupon Codes',
      redemptionHistory: 'Redemption History',
      code: 'Code',
      discount: 'Discount',
      used: 'Used',
      limit: 'Limit',
      expires: 'Expires',
      noExpiry: 'No expiry',
      unlimited: 'Unlimited',
      noCoupons: 'No coupons created yet',
      noRedemptions: 'No redemptions yet',
      user: 'User',
      redeemedAt: 'Redeemed At',
      supportMessages: 'Support Messages',
      noMessages: 'No support messages',
      from: 'From',
      subject: 'Subject',
      date: 'Date',
      view: 'View',
      accessDenied: 'Access Denied',
      accessDeniedDesc: 'You do not have admin privileges.'
    },

    // Layout/Navigation
    nav: {
      dashboard: 'Dashboard',
      campaigns: 'Campaigns',
      contacts: 'Contacts',
      companies: 'Companies',
      help: 'Help',
      settings: 'Settings',
      admin: 'Admin',
      signOut: 'Sign Out'
    },

    // Common/Shared
    common: {
      loading: 'Loading...',
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      create: 'Create',
      update: 'Update',
      search: 'Search',
      filter: 'Filter',
      actions: 'Actions',
      yes: 'Yes',
      no: 'No',
      confirm: 'Confirm',
      close: 'Close',
      back: 'Back',
      next: 'Next',
      finish: 'Finish',
      error: 'Error',
      success: 'Success',
      warning: 'Warning',
      info: 'Info',
      perMonth: '/month',
      month: 'month',
      year: 'year'
    },

    // Upgrade Prompt
    upgradePrompt: {
      title: 'Upgrade Required',
      description: 'This feature is available on paid plans only.',
      upgradeTo: 'Upgrade to',
      orHigher: 'or higher',
      benefits: 'Unlock more features:',
      viewPlans: 'View Plans',
      maybeLater: 'Maybe Later'
    }
  },

  lt: {
    // Auth Component
    auth: {
      welcomeBack: 'Sveiki Sugrįžę',
      createAccount: 'Sukurti Paskyrą',
      signInSubtitle: 'Prisijunkite prie savo paskyros',
      createAccountSubtitle: 'Pradėkite šaltų el. laiškų kampanijas',
      continueWithGoogle: 'Tęsti su Google',
      or: 'arba',
      email: 'El. paštas',
      password: 'Slaptažodis',
      signIn: 'Prisijungti',
      signUp: 'Registruotis',
      forgotPassword: 'Pamiršote slaptažodį?',
      dontHaveAccount: 'Neturite paskyros?',
      alreadyHaveAccount: 'Jau turite paskyrą?',
      checkEmailConfirmation: 'Patikrinkite el. paštą dėl patvirtinimo nuorodos!',
      backToLanding: 'Atgal į Pagrindinį'
    },

    // Dashboard
    dashboard: {
      title: 'Valdymo Skydelis',
      welcome: 'Sveiki atvykę į Contactium',
      quickStats: 'Greita Statistika',
      totalCampaigns: 'Viso Kampanijų',
      runningCampaigns: 'Vykdomos',
      completedCampaigns: 'Užbaigtos',
      emailsSent: 'Išsiųsta Laiškų',
      recentCampaigns: 'Naujausi Kampanijos',
      viewAll: 'Žiūrėti Visas',
      createCampaign: 'Sukurti Naują Kampaniją',
      noCampaigns: 'Dar nėra kampanijų',
      noCampaignsDesc: 'Sukurkite pirmąją kampaniją norėdami pradėti siųsti šaltus el. laiškus',
      status: 'Būsena',
      recipients: 'Gavėjai',
      sent: 'Išsiųsta',
      actions: 'Veiksmai',
      send: 'Siųsti',
      view: 'Žiūrėti',
      sending: 'Siunčiama...',
      confirmSend: 'Ar tikrai norite išsiųsti',
      confirmSendDetails: 'Tai sugeneruos ir išsiųs personalizuotus el. laiškus visiems gavėjams.',
      campaignLimitReached: 'Pasiektas kampanijų limitas! Turite',
      campaignLimitOf: 'iš',
      campaignLimitUpgrade: 'kampanijų. Atnaujinkite planą norėdami sukurti daugiau kampanijų.',
      sendSuccess: 'Kampanija išsiųsta sėkmingai!',
      emailsSentCount: 'laiškai išsiųsti',
      emailsFailedCount: 'nepavyko',
      sendFailed: 'Nepavyko išsiųsti kampanijos:',
      expired: 'Pasibaigęs',
      expiresIn: 'Baigiasi po',
      days: 'dienų'
    },

    // Campaigns
    campaigns: {
      title: 'Kampanijos',
      searchPlaceholder: 'Ieškoti kampanijų...',
      filter: 'Filtruoti',
      all: 'Visos',
      draft: 'Juodraštis',
      running: 'Vykdomos',
      completed: 'Užbaigtos',
      paused: 'Pristabdytos',
      noCampaigns: 'Kampanijų nerasta',
      createFirst: 'Sukurkite pirmąją kampaniją',
      name: 'Pavadinimas',
      status: 'Būsena',
      recipients: 'Gavėjai',
      sent: 'Išsiųsta',
      createdAt: 'Sukurta',
      actions: 'Veiksmai'
    },

    // Create Campaign
    createCampaign: {
      title: 'Sukurti Naują Kampaniją',
      step: 'Žingsnis',
      of: 'iš',
      campaignDetails: 'Kampanijos Duomenys',
      selectContacts: 'Pasirinkti Kontaktus',
      emailSettings: 'El. Pašto Nustatymai',
      reviewAndCreate: 'Peržiūra ir Sukūrimas',
      campaignName: 'Kampanijos Pavadinimas',
      campaignNamePlaceholder: 'Įveskite kampanijos pavadinimą',
      selectContactList: 'Pasirinkti Kontaktų Sąrašą',
      selectContactListPlaceholder: 'Pasirinkite kontaktų sąrašą',
      noContactLists: 'Nėra kontaktų sąrašų',
      createContactList: 'Pirmiausia sukurkite kontaktų sąrašą',
      selectedContacts: 'Pasirinkti Kontaktai',
      emailSubject: 'El. Laiško Tema',
      emailSubjectPlaceholder: 'Įveskite el. laiško temą',
      valueProposition: 'Vertės Pasiūlymas',
      valuePropositionPlaceholder: 'Apibūdinkite savo vertės pasiūlymą, kad AI sugeneruotų personalizuotus laiškus',
      aiModel: 'AI Modelis',
      selectModel: 'Pasirinkite AI modelį',
      tone: 'Tonas',
      selectTone: 'Pasirinkite toną',
      professional: 'Profesionalus',
      friendly: 'Draugiškas',
      casual: 'Neoficialus',
      formal: 'Oficialus',
      length: 'Laiško Ilgis',
      selectLength: 'Pasirinkite ilgį',
      short: 'Trumpas',
      medium: 'Vidutinis',
      long: 'Ilgas',
      language: 'Kalba',
      selectLanguage: 'Pasirinkite kalbą',
      back: 'Atgal',
      continue: 'Tęsti',
      createCampaign: 'Sukurti Kampaniją',
      creating: 'Kuriama...',
      fillAllFields: 'Prašome užpildyti visus būtinus laukus',
      campaignCreated: 'Kampanija sukurta sėkmingai!',
      errorCreating: 'Klaida kuriant kampaniją:'
    },

    // Contact Lists
    contactLists: {
      title: 'Kontaktų Sąrašai',
      createNew: 'Sukurti Naują Sąrašą',
      searchPlaceholder: 'Ieškoti kontaktų sąrašų...',
      noLists: 'Dar nėra kontaktų sąrašų',
      createFirst: 'Sukurkite pirmąjį kontaktų sąrašą norėdami organizuoti kontaktus',
      name: 'Pavadinimas',
      contacts: 'Kontaktai',
      createdAt: 'Sukurta',
      actions: 'Veiksmai',
      view: 'Žiūrėti',
      edit: 'Redaguoti',
      delete: 'Ištrinti',
      confirmDelete: 'Ar tikrai norite ištrinti šį kontaktų sąrašą?',
      deleteSuccess: 'Kontaktų sąrašas ištrintas sėkmingai',
      deleteError: 'Klaida trinant kontaktų sąrašą'
    },

    // Companies (Database)
    companies: {
      title: 'Įmonių Duomenų Bazė',
      subtitle: 'Naršykite ir pasirinkite įmones iš mūsų patvirtintos duomenų bazės',
      searchPlaceholder: 'Ieškoti įmonių...',
      filterByIndustry: 'Filtruoti pagal Pramonę',
      allIndustries: 'Visos Pramonės',
      filterByCity: 'Filtruoti pagal Miestą',
      allCities: 'Visi Miestai',
      showing: 'Rodoma',
      of: 'iš',
      companies: 'įmonių',
      noCompanies: 'Įmonių nerasta',
      adjustFilters: 'Pabandykite patikslinti paiešką arba filtrus',
      companyName: 'Įmonės Pavadinimas',
      industry: 'Pramonė',
      city: 'Miestas',
      email: 'El. paštas',
      phone: 'Telefonas',
      actions: 'Veiksmai',
      addToList: 'Pridėti prie Sąrašo',
      selectList: 'Pasirinkite kontaktų sąrašą',
      companyAdded: 'Įmonė pridėta prie kontaktų sąrašo',
      errorAdding: 'Klaida pridedant įmonę prie sąrašo'
    },

    // Settings
    settings: {
      title: 'Nustatymai',
      profile: 'Profilis',
      smtp: 'SMTP Konfigūracija',
      subscription: 'Prenumerata ir Apskaita',
      emailSettings: 'El. Pašto Nustatymai',
      profileEmail: 'El. paštas',
      profileName: 'Vardas',
      profileNamePlaceholder: 'Jūsų vardas',
      save: 'Išsaugoti Pakeitimus',
      saving: 'Saugoma...',
      saved: 'Nustatymai išsaugoti sėkmingai',
      smtpHost: 'SMTP Serveris',
      smtpHostPlaceholder: 'smtp.gmail.com',
      smtpPort: 'SMTP Prievadas',
      smtpPortPlaceholder: '587',
      smtpUser: 'SMTP Vartotojas',
      smtpUserPlaceholder: 'jusu-el-pastas@gmail.com',
      smtpPassword: 'SMTP Slaptažodis',
      smtpPasswordPlaceholder: 'Jūsų programos slaptažodis',
      smtpSecure: 'Naudoti SSL/TLS',
      testConnection: 'Testuoti Ryšį',
      testing: 'Testuojama...',
      connectionSuccess: 'SMTP ryšys sėkmingas!',
      connectionFailed: 'SMTP ryšys nepavyko:',
      smtpInstructions: 'Sukonfigūruokite SMTP nustatymus el. laiškams siųsti. Gmail naudokite programai skirtą slaptažodį.',
      fromName: 'Siuntėjo Vardas',
      fromNamePlaceholder: 'Jūsų Įmonė',
      fromEmail: 'Siuntėjo El. paštas',
      fromEmailPlaceholder: 'jusu@imone.lt'
    },

    // Subscription
    subscription: {
      title: 'Prenumerata ir Apskaita',
      subtitle: 'Tvarkykite prenumeratą ir peržiūrėkite naudojimą',
      currentPlan: 'Dabartinis Planas',
      freePlan: 'Nemokamas Planas',
      starterPlan: 'Pradedančiojo Planas',
      professionalPlan: 'Profesionalus Planas',
      active: 'Aktyvus',
      canceled: 'Atšauktas',
      pastDue: 'Laukiama Mokėjimo',
      monthlyUsage: 'Mėnesinis El. Laiškų Naudojimas',
      emailsSent: 'laiškai išsiųsti',
      remaining: 'liko',
      limitReached: 'Limitas pasiektas',
      upgradePrompt: 'Pasiekėte mėnesinį el. laiškų limitą. Atnaujinkite norėdami siųsti daugiau.',
      lowEmailsWarning: 'Baigiasi el. laiškai? Atnaujinkite norėdami tęsti kampanijas be pertraukų.',
      upgradeTo: 'Atnaujinti į',
      manageSubscription: 'Tvarkyti Prenumeratą',
      billingInfo: 'Apskaitos Informacija',
      nextBillingDate: 'Kita Apskaitos Data',
      amount: 'Suma',
      paymentMethod: 'Mokėjimo Būdas',
      recentInvoices: 'Naujausi Sąskaitos',
      paid: 'Apmokėta',
      pending: 'Laukiama',
      void: 'Anuliuota',
      failed: 'Nepavyko',
      downloadPDF: 'PDF',
      haveCoupon: 'Turite Nuolaidų Kodą?',
      enterCoupon: 'Įveskite nuolaidų kodą',
      couponApplied: 'Nuolaidų kodas bus pritaikytas prie apmokėjimo',
      cancelAnytime: 'Galite atšaukti arba keisti prenumeratą bet kada per klientų portalą. Nereikalaujame ilgalaikių įsipareigojimų.',
      whyUpgrade: 'Kodėl Atnaujinti?',
      benefit1: 'Siųskite daugiau laiškų ir pasiekite daugiau potencialių klientų',
      benefit2: 'Valdykite kelias kampanijas vienu metu',
      benefit3: 'Neribota AI el. laiškų generacija',
      benefit4: 'Plėskite šaltų el. laiškų išsiuntimus',
      benefit5: 'Pirmumo el. pašto pagalba'
    },

    // Support
    support: {
      title: 'Pagalba ir Palaikymas',
      searchPlaceholder: 'Ieškoti pagalbos...',
      gettingStarted: 'Pradžia',
      gettingStartedDesc: 'Išmokite Contactium pagrindus',
      campaigns: 'Kampanijų Valdymas',
      campaignsDesc: 'Kampanijų kūrimas ir valdymas',
      contacts: 'Kontaktų Valdymas',
      contactsDesc: 'Kontaktų sąrašų organizavimas',
      smtp: 'SMTP Nustatymas',
      smtpDesc: 'El. pašto siuntimo konfigūravimas',
      billing: 'Apskaita ir Planai',
      billingDesc: 'Prenumeratos ir mokėjimo pagalba',
      contactSupport: 'Susisiekti su Palaikymu',
      contactSupportDesc: 'Gaukite pagalbą iš mūsų komandos',
      sendMessage: 'Atsiųskite mums žinutę',
      subject: 'Tema',
      subjectPlaceholder: 'Kaip galime padėti?',
      message: 'Žinutė',
      messagePlaceholder: 'Apibūdinkite savo problemą ar klausimą...',
      send: 'Siųsti Žinutę',
      sending: 'Siunčiama...',
      messageSent: 'Žinutė išsiųsta sėkmingai! Netrukus su jumis susisieksime.',
      messageError: 'Klaida siunčiant žinutę. Prašome bandyti dar kartą.'
    },

    // Admin Panel
    admin: {
      title: 'Administratoriaus Skydelis',
      overview: 'Apžvalga',
      users: 'Vartotojai',
      coupons: 'Nuolaidų Kodai',
      support: 'Palaikymo Žinutės',
      totalUsers: 'Viso Vartotojų',
      freeUsers: 'Nemokamas Planas',
      paidUsers: 'Mokami Planai',
      totalRevenue: 'Bendros Pajamos',
      searchUsers: 'Ieškoti vartotojų...',
      filterPlan: 'Filtruoti pagal Planą',
      allPlans: 'Visi Planai',
      email: 'El. paštas',
      plan: 'Planas',
      status: 'Būsena',
      joined: 'Prisijungė',
      actions: 'Veiksmai',
      createCoupon: 'Sukurti Nuolaidų Kodą',
      couponCode: 'Nuolaidų Kodas',
      couponCodePlaceholder: 'VASARA2024',
      discountType: 'Nuolaidos Tipas',
      percentOff: 'Procentinė Nuolaida',
      amountOff: 'Fiksuota Nuolaida',
      percentValue: 'Nuolaida (%)',
      percentPlaceholder: '20',
      amountValue: 'Nuolaida (€)',
      amountPlaceholder: '10',
      duration: 'Trukmė',
      once: 'Vieną kartą',
      repeating: 'Pasikartojantis',
      forever: 'Amžinai',
      durationMonths: 'Trukmė (Mėnesiai)',
      maxRedemptions: 'Maks. Panaudojimų',
      maxRedemptionsPlaceholder: 'Palikite tuščią neribotam',
      expiresAt: 'Galioja Iki',
      createCouponBtn: 'Sukurti Kodą',
      creating: 'Kuriama...',
      activeCoupons: 'Aktyvūs Nuolaidų Kodai',
      redemptionHistory: 'Panaudojimų Istorija',
      code: 'Kodas',
      discount: 'Nuolaida',
      used: 'Panaudota',
      limit: 'Limitas',
      expires: 'Galioja',
      noExpiry: 'Be galiojimo',
      unlimited: 'Neribota',
      noCoupons: 'Dar nesukurta nuolaidų kodų',
      noRedemptions: 'Dar nėra panaudojimų',
      user: 'Vartotojas',
      redeemedAt: 'Panaudota',
      supportMessages: 'Palaikymo Žinutės',
      noMessages: 'Nėra palaikymo žinučių',
      from: 'Nuo',
      subject: 'Tema',
      date: 'Data',
      view: 'Žiūrėti',
      accessDenied: 'Prieiga Uždrausta',
      accessDeniedDesc: 'Neturite administratoriaus teisių.'
    },

    // Layout/Navigation
    nav: {
      dashboard: 'Skydelis',
      campaigns: 'Kampanijos',
      contacts: 'Kontaktai',
      companies: 'Įmonės',
      help: 'Pagalba',
      settings: 'Nustatymai',
      admin: 'Administravimas',
      signOut: 'Atsijungti'
    },

    // Common/Shared
    common: {
      loading: 'Kraunama...',
      save: 'Išsaugoti',
      cancel: 'Atšaukti',
      delete: 'Ištrinti',
      edit: 'Redaguoti',
      create: 'Sukurti',
      update: 'Atnaujinti',
      search: 'Ieškoti',
      filter: 'Filtruoti',
      actions: 'Veiksmai',
      yes: 'Taip',
      no: 'Ne',
      confirm: 'Patvirtinti',
      close: 'Uždaryti',
      back: 'Atgal',
      next: 'Toliau',
      finish: 'Baigti',
      error: 'Klaida',
      success: 'Sėkmingai',
      warning: 'Įspėjimas',
      info: 'Informacija',
      perMonth: '/mėn',
      month: 'mėnuo',
      year: 'metai'
    },

    // Upgrade Prompt
    upgradePrompt: {
      title: 'Reikalingas Atnaujinimas',
      description: 'Ši funkcija prieinama tik mokamose versijose.',
      upgradeTo: 'Atnaujinti į',
      orHigher: 'arba aukštesnį',
      benefits: 'Atrakinkite daugiau funkcijų:',
      viewPlans: 'Žiūrėti Planus',
      maybeLater: 'Galbūt Vėliau'
    }
  }
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    // Load from localStorage or default to 'en'
    return localStorage.getItem('language') || 'en'
  })

  useEffect(() => {
    // Save to localStorage when language changes
    localStorage.setItem('language', language)
  }, [language])

  const t = (key) => {
    const keys = key.split('.')
    let value = translations[language]

    for (const k of keys) {
      value = value?.[k]
    }

    return value || key
  }

  const value = {
    language,
    setLanguage,
    t,
    translations: translations[language]
  }

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}
