-- Migration: Add Lithuanian business activity tags
-- Date: 2024-11-16
-- Description: Adds 288 Lithuanian business activity categories as tags

INSERT INTO company_tags (name, category, color, description) VALUES
  ('Akmens gaminiai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Akumuliatoriai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Antrinės žaliavos', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Antstoliai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Apranga, drabužiai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Apsaugos sistemos pa..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Apskaita', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Apželdinimas ir apli..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Architektai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Atliekų tvarkymas', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Audiniai, patalynė', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Auditas', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Aukštalipių paslaugo..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Aukštesniojo ir prof..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Aukštosios mokyklos,..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Autobusų, mikroautob..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Autokosmetika', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Automatizavimas, aut..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Automobilių dalys', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Automobilių garso ir..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Automobilių nuoma', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Automobilių parkavim..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Automobilių pervežim..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Automobilių plovyklo..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Automobilių prekyba', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Automobilių stiklai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Automobilių techninė..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Automobilių šaldymo ..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Autoservisai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Autosąvartynai, naud..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Avalynė, batai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Avarinės tarnybos', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Azartiniai lošimai, ..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Baldai (gamyba)', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Baldai (prekyba)', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Baldų gamybos medžia..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Bankai, bankinės ope..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Bendruomenės', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Betonas ir betono ga..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Bibliotekos, archyva..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Biuro įranga', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Buities paslaugos', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Buitinė technika', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Chemijos pramonė, ga..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Darbo apranga', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Darbo paieška, įdarb..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Darbo sauga', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Daržininkystė, sodin..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Daržovės', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Dažai, lakai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Didmeninė prekyba', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Dovanos', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Draudimas', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Dujos, dujų įranga', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Durys, raktai, spyno..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Dviračiai, paspirtuk..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Ekspedijavimas', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Eksportas', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Elektros dalys ir įr..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Elektros instaliacij..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Elektros montavimo m..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Elektros varikliai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Energetika', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Fasadas, fasado apda..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Fejerverkai, pirotec..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Finansai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Fotografijos paslaug..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Galanterija', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Gamtos apsauga', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Gamyba', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Geležinkelių transpo..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Geodezija, kartograf..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Geologija', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Ginklai, savisaugos ..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Globa ir priežiūra', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Grafika, dizainas', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Greitieji kreditai, ..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Grindys, grindų dang..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Griovimas, gręžimas', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Grožio salonai ir ki..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Grūdininkystė', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Guoliai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Gyvuliai, žvėrys, pa..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Gyvūnų globa', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Gėlės ir dekoratyvin..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Gėrimai (alkoholinia..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Gėrimai (nealkoholin..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Hidraulika, pneumati..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Higienos reikmenys', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Importas', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Indai, valgymo įrank..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Individuali veikla', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Informacijos teikima..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Institutai, mokslini..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Interjero apdailos m..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Interneto parduotuvė..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Interneto paslaugos', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Interneto svetainių ..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Intymios prekės', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Investicinė veikla', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Inžineriniai tinklai..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Juvelyriniai dirbini..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Kailiai ir jų dirbin..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Kaimo turizmas', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Kalbų kursai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Kanceliarijos prekės', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Kava, arbata', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Kavinės, klubai, bar..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Keleivių pervežimas', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Kelionės', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Kelių tiesimas, remo..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Kenkėjų naikinimas, ..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Kepyklos', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Keramikos gaminiai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Kino paslaugos', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Kita veikla', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Knygos ir knygynai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Kompiuteriai ir prog..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Kompiuterių programi..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Kompiuterių remontas..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Kompresoriai, siurbl..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Komunalinė technika', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Komunalinės paslaugo..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Konditerija, saldumy..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Konsultacijų paslaug..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Kontrolės tarnybos', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Kosmetika, parfumeri..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Krautuvai, keltuvai,..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Kriptovaliutos', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Kultūros centrai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Kuras, naftos produk..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Labdara, parama', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Laboratorijos, įrang..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Laidojimo paslaugos,..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Laikrodžiai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Laivų remontas, stat..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Langai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Logistikos paslaugos', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Lombardai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Maistas į namus, biu..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Maisto gamyba', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Maisto gamybos ir pe..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Maisto parduotuvės', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Maisto produktai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Malkos, kuras šildym..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Matavimo prietaisai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Mažmeninė prekyba', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Medicininė įranga', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Medicinos įstaigos, ..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Mediena, jos gaminia..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Mediniai namai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Melioracija, meliora..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Meno mokymo įstaigos', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Meno salonai ir gale..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Metalas, apdirbimas,..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Metalo konstrukcijos..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Metalo, medžio apdir..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Metalų pardavimas, s..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Miškininkystė', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Miško gėrybės', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Miško, sodo, vejos t..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Mokyklos, bendrojo l..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Mokymo kursai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Motociklai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Muitinių paslaugos, ..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Muziejai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Muzikos instrumentai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Mėsa, mėsos produkta..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Naminiai gyvūnai, ma..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Namų savininkų bendr..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Naudingosios iškasen..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Nekilnojamasis turta..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Notarų biurai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Odontologija, paslau..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Odos gaminiai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Optika, akiniai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Oro transportas, avi..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Padangos, ratlankiai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Pagalba kelyje', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Paminklai, antkapiai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Pardavimo automatai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Parodos, mugės', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Pastatų administravi..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Patalpų nuoma', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Patentinės paslaugos', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Pašarai, gyvulinis m..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Pašto paslaugos, kur..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Perkraustymas', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Personalo atranka', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Pienas, pieno produk..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Pirtys ir baseinai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Plastikas, guma, jų ..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Plovyklų, autoservis..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Poilsio namai, sanat..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Politinės organizaci..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Popierius, jo gamini..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Pramogos ir poilsis', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Pramonės įrengimai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Prekybos įranga', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Priešgaisrinė sauga,..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Projektavimas', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Psichologai, psichot..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Reklamos paslaugos', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Religinės organizaci..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Renginių organizavim..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Restoranų, kavinių, ..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('SEO paslaugos', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('SPA centrai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Sandėliavimas', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Santechnika', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Saugos tarnybos', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Savivaldybės', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Sendaikčiai, antikva..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Seniūnijos', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Sertifikavimo paslau..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Sienos, lubos', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Siuvimas, medžiagos', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Skolų išieškojimas', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Socialinės paslaugos', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Sodininkų bendrijos', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Spaustuvės, leidyba', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Sporto organizacijos', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Sporto paslaugos, sp..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Sporto, turizmo reik..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Statyba', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Statybinės medžiagos', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Statybos technika, į..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Stiklas ir jo gamini..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Stogų dangos, paslau..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Sunkvežimių pardavim..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Suvirinimas ir suvir..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Sveiki produktai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Sąjungos, fondai, as..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Tabakas', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Taksi paslaugos', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Tara, pakuotės', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Tarpininkavimas', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Teatrai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Technologinė įranga', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Teisinės paslaugos', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Teisėtvarka', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Telekomunikacijos, r..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Televizija ir radija..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Tepalai, alyvos', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Transporto paslaugos', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Trąšos', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Turgavietės', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Turto vertinimas', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Tvirtinimo detalės, ..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Tyrimai, ekspertizės', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Vaikų būreliai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Vaikų darželiai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Vaikų prekės', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Vairavimo mokymo pas..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Vaisiai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Vaistai, medicininės..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Vaizdo stebėjimo sis..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Valstybinės instituc..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Valymo priemonės', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Vamzdynai, vandentie..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Vandens transportas', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Vartai, tvoros', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Vertimas', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Vestuviniai drabužia..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Veterinarija', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Video ir audio apara..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Video ir audio įraša..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Viešbučiai, moteliai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Vėdinimas, kondicion..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Įmonių steigimas', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Įrankiai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Šaldymo įrenginiai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Šaldyti maisto produ..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Šeimynos', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Šildymas, įrenginiai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Šiltinimas, renovaci..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Švaros, valymo pasla..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Šviesos sistemos, šv..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Ūkio prekės', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Žaislai', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Žaliuzės, užuolaidos..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Žemės ūkio technika', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Žemės ūkis, paslaugo..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Žemėtvarka', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Židiniai, krosnys', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Žiniasklaida', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Žuvininkystė, žuvies..', 'industry', '#3b82f6', 'Lithuanian business activity'),
  ('Žūklės ir medžioklės..', 'industry', '#3b82f6', 'Lithuanian business activity')
ON CONFLICT (name) DO NOTHING;
